### ISSUE TITLE
Organization

### ISSUE THREAD

**Issue by wilbennett** [MillerMark/CodeRushed-1#8]
Mark,

In the show today, you were trying to group items together in columns by using HTML elements.  I think this is the wrong way to go.  You should view it more like creating classes/interfaces in C# - keep everything small and encapsulated and then you can combine however you want.   You can add multiple class names to each section/element so you can hide/show an entire group of elements/sections using a single style.  You can swap in different layouts even allowing users to select the layout they want.

If you create small divs with the elements that make up a cohesive group, you can then lay them out in the CSS however you want.  This provides much better flexibility, especially if you later want to convert to a proper framework such as Angular or React (each section becomes a component).  The more you pack into the HTML the more rigid you make the design.

With the grid layout, you just specify how you want the layout to look by stacking the individual sections how you want.  Note that you can have elements span multiple columns and/or rows.

### e.g.

Create specific sections: create, modify, canvas, scale, nav, preview, draw, animate, share, load

Now just lay them out:

  'create modify scale'
  'nav     preview scale'
 ' animate share load'
 'preview preview preview'

Notice preview spans three columns and scale spans two rows.  You are free to lay it out however you want.  All the pieces are separate so you have ultimate flexibility.  If you combine them in HTML then you are stuck with that combination and if you want to adapt the design for different screen sizes or landscape vs portrait, it becomes unnecessarily difficult.

Wil

**Comment by MillerMark** [comment]
Is there a way to establish a layout that is embedded inside a div in a second layout? Can I nest layouts or should I be thinking big picture (individual positioning of every element) for this entire thing?

- Mark

**Comment by wilbennett** [comment]
Yes you can.  If you look at the CSS, there are two layouts being used.  The overall layout is using the grid format - two columns because that's all we had so far.  Individual sections (cells) are using the flex layout option.  You can mix and match however you want - there are no constraints.  Just keep in mind that when you nest the divs you are locked into that configuration.

You can view the divs like a control in xaml.  Whatever you put in that control can be styled however you want but stays with that control.  You can layout as many of those controls in whatever configuration you want.  So it's like the difference between having a combobox or a textbox and a button separately.

**Comment by wilbennett** [comment]
Here are a couple links that explain the layout options:

https://www.w3schools.com/css/css_grid_container.asp
https://www.w3schools.com/css/css3_flexbox.asp

**Comment by wilbennett** [comment]
I forgot to put my disclaimer:

I'm not a web guy so my opinions are not based on real world experience.  In fact, I've never used grid or flex layout before - I'm used to tables.  So please feel free to disagree and choose a different approach if you feel it's better.  We will both learn from each other.

**Comment by MillerMark** [comment]
Nice disclaimer! :-)
